### ISSUE TITLE
Failed to connect to mirrors6.shuosc.org port 443: Connection refused

### ISSUE THREAD

**Issue by l2dy** [shuopensourcecommunity/mirrors.shuosc.org#18]
```
$ curl -v 'https://mirrors6.shuosc.org/'
*   Trying 2001:da8:8006:11:225:90ff:fee1:813e...
* TCP_NODELAY set
* Connection failed
* connect to 2001:da8:8006:11:225:90ff:fee1:813e port 443 failed: Connection refused
* Failed to connect to mirrors6.shuosc.org port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to mirrors6.shuosc.org port 443: Connection refused
```

**Comment by zhonger** [comment]
You are right. Because our nginx cannot be `ipv6 only`, the `mirrors6.shuosc.org` is down. What's more, we are planning to change the OS from `CentOS 6` to `Ubuntu 16.04` on our mirror server recently. In a couple of days, we will do it and the problem will be fixed together.  In this period, the mirror server will be transferred to another server for a short time. After all works are done, everything will be OK.

**Comment by l2dy** [comment]
Can you elaborate on "our nginx cannot be `ipv6 only`"? Shouldn't `ipv6 only` be achieved with DNS?

**Comment by zhonger** [comment]
The `ipv6 only` has be achieved with DNS, but `nginx` don't make it. If we want to make nginx just listening to `ipv6`, we should change some content of `nginx.conf`. Now we want to rebuild the OS of mirror server, so we choose to fix this problem after that. 
Thanks for your suggestions all the same.

**Comment by zhonger** [comment]
@l2dy Now we have just fixed the `mirrors6.shuosc.org` error. Please check it.
And I have figured out why it is. All DNS records are resolved to the mirror server by default. So the mirror server will not be resolved only by ipv6. Now I have removed the default record and it's ok.
