### ISSUE TITLE
some repos' update time is not updated

### ISSUE THREAD

**Issue by bucketzxm** [shuopensourcecommunity/mirrors.shuosc.org#2]
for example, npm repo's  update time shows 2016-12-30 23:00:00

**Comment by zhonger** [comment]
Because `npm` repo is built with `cnpm/cnpmjs.org` in another server, and some repo is mirrored by `wget` with manual operation. 
We are so happy to tell you that we just update the mirrors site to V2 [https://mirrors.shuosc.org](https://mirrors.shuosc.org), and there is no longer some problem just like you say. Thank you for contacting us.
Furthermore, if you want to know the `npm` repo's status, you have to visit [https://npm.shuosc.org](https://npm.shuosc.org).
Thank you !
