### ISSUE TITLE
Anaconda mirrors 404

### ISSUE THREAD

**Issue by liwt31** [shuopensourcecommunity/mirrors.shuosc.org#29]
The following links shows 404.
https://mirrors.shu.edu.cn/anaconda/pkgs/index.html
https://mirrors.shu.edu.cn/anaconda/archive/index.html

EDIT: Not sure this is expected or not. For pkgs mirrors, https://mirrors.shu.edu.cn/anaconda/pkgs/main/ can be used directly

**Comment by liwt31** [comment]
Also, [https://mirrors.shu.edu.cn/anaconda/pkgs/main/linux-64/repodata.json](https://mirrors.shu.edu.cn/anaconda/pkgs/main/linux-64/repodata.json) seems corrupted. Can't parsed by JSON.

**Comment by zhonger** [comment]
Thank you for reporting this. 
Actually, this Anaconda mirror is not reliable because of its simple `wget` mirror way. In the future, we would like to analyze Anaconda's directory and build a mirror script especially. 
Due that I use` pypi` rather than Anaconda, it would be turned over another maintainer who is familiar with this.
Thanks a lot again. 
We would fix these problems you reported. But there is still much work to do.

**Comment by AdrianDuan** [comment]
Thanks for your report.
We will try to use [cas-mirror](https://docs.anaconda.com/anaconda-repository/admin-guide/sys-mgmt/components/use-cas-mirror/) to fix this problem soon.
